
CREATE TABLE IF NOT EXISTS users ( -- hello
	id		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	username	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "groups" (
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name	TEXT NOT NULL UNIQUE
);

CREATE TABLE jobs (
	id		INT NOT NULL PRIMARY KEY,
	name	TEXT NOT NULL,
	num_nodes INT
);
